// Regenerate src/settings-keys.ts SCHEMA_KEYS from the official Claude Code
// settings JSON schema. APP_ONLY_KEYS (keys the running app writes ahead of the
// published schema) are preserved verbatim. No args rewrites the file; --check
// prints drift and exits non-zero without writing. Network failure exits 2 in
// both modes (never a silent pass). The weekly settings-schema-drift workflow
// runs the write mode and opens a PR when SCHEMA_KEYS changes. Run via tsx.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { SETTINGS_SCHEMA_URL } from '../src/config.ts';

/** Absolute path to the module this script keeps in sync. */
const TARGET = fileURLToPath(new URL('../src/settings-keys.ts', import.meta.url));

/** Sort case-insensitively and drop duplicates; the canonical shape for both key arrays. */
export function canonicalizeKeys(keys: string[]): string[] {
  return [...new Set(keys)].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
}

/** Extract the quoted string entries of a `const <name> = [ ... ];` array literal from TS source. */
export function parseKeyArray(source: string, name: string): string[] {
  const match = new RegExp(`(?:export )?const ${name} = \\[([^\\]]*)\\]`).exec(source);
  if (match === null) throw new Error(`could not find ${name} in settings-keys.ts`);
  return [...match[1].matchAll(/'([^']+)'/g)].map((entry) => entry[1]);
}

/** Render the full settings-keys.ts file content from the two key groups (both canonicalized). */
export function renderSettingsKeysFile(schemaKeys: string[], appOnlyKeys: string[]): string {
  const fmt = (arr: string[]): string =>
    canonicalizeKeys(arr)
      .map((k) => `  '${k}',`)
      .join('\n');
  const header = [
    '/**',
    ' * Top-level keys recognized in `~/.claude/settings.json`, used by the',
    ' * `nomad doctor` schema-drift check. Split by provenance so the schema half',
    ' * can be re-synced mechanically.',
    ' *',
    ' * `SCHEMA_KEYS`: the documented properties from the official Claude Code',
    ' * settings JSON schema (https://json.schemastore.org/claude-code-settings.json).',
    ' * Regenerated by scripts/sync-settings-keys.ts (run weekly by the',
    ' * settings-schema-drift workflow); do not hand-edit this array.',
    ' *',
    ' * `APP_ONLY_KEYS`: keys Claude Code writes to settings.json that the published',
    ' * schema has not caught up to yet (the running app runs ahead of the schema).',
    ' * These cannot be derived from the schema and are hand-maintained.',
    ' */',
  ].join('\n');
  return `${header}
export const SCHEMA_KEYS = [
${fmt(schemaKeys)}
];

export const APP_ONLY_KEYS = [
${fmt(appOnlyKeys)}
];

/** Union of schema-documented and app-only settings keys; unknown top-level keys trigger a doctor WARN. */
export const KNOWN_SETTINGS_KEYS = new Set<string>([...SCHEMA_KEYS, ...APP_ONLY_KEYS]);
`;
}

/** Fetch the schema and return its top-level property names. Throws on any failure. */
async function fetchSchemaKeys(): Promise<string[]> {
  const res = await fetch(SETTINGS_SCHEMA_URL);
  if (!res.ok) throw new Error(`schema fetch failed: HTTP ${res.status}`);
  const schema = (await res.json()) as { properties?: Record<string, unknown> };
  if (typeof schema.properties !== 'object' || schema.properties === null) {
    throw new Error('schema response has no properties object');
  }
  return Object.keys(schema.properties);
}

/** CLI entry: diff (and in write mode regenerate) SCHEMA_KEYS against the live schema. */
async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  const source = readFileSync(TARGET, 'utf8');
  const currentSchema = canonicalizeKeys(parseKeyArray(source, 'SCHEMA_KEYS'));
  const appOnly = parseKeyArray(source, 'APP_ONLY_KEYS');

  let live: string[];
  try {
    live = canonicalizeKeys(await fetchSchemaKeys());
  } catch (err) {
    console.error(`error: ${(err as Error).message}`);
    process.exit(2);
  }

  const added = live.filter((k) => !currentSchema.includes(k));
  const removed = currentSchema.filter((k) => !live.includes(k));

  if (check) {
    if (added.length === 0 && removed.length === 0) {
      console.log('settings schema in sync; no drift.');
      return;
    }
    if (added.length > 0) console.log(`added: ${added.join(', ')}`);
    if (removed.length > 0) console.log(`removed: ${removed.join(', ')}`);
    process.exit(1);
  }

  // Only write when the rendered output actually differs from disk. Writing
  // unconditionally re-emitted the canonical header (e.g. after the script was
  // renamed) and produced a phantom comment-only diff that the weekly workflow
  // turned into a no-op PR every run. Idempotent write mode prevents that.
  const next = renderSettingsKeysFile(live, appOnly);
  if (next === source) {
    console.log('settings schema in sync; file unchanged.');
    return;
  }
  writeFileSync(TARGET, next);
  console.log(
    added.length > 0 || removed.length > 0
      ? `updated SCHEMA_KEYS (+${added.length} -${removed.length}).`
      : 'rewrote settings-keys.ts (formatting only; keys unchanged).',
  );
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
